/* 
 * Resource generated for file:
 *    SCI_small.gif (zlib, base64) (binary file)
 */
static const unsigned long file_SCI_small_gif_length         = 1540;
static const unsigned long file_SCI_small_gif_decoded_length = 1144;

static const unsigned char file_SCI_small_gif[] = 
  "eNoBeASH+0dJRjg5YVAAIwDEAAD7+/z5+fr19fbo6Ong4OHDw8S3t7irq6zV1tfOz9BzdH"
  "SbnJz////9/f38/Pz7+/v4+Pj39/fz8/Pv7++Pj4+JiYlbW1s7OzsCAgIAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAsAAAAAFAAIwBABf8gJo5kaZ5oqq7syLwFdj3vKyU1s4hF7g80hczHiA"
  "wmDeKrYaA4K4sCREkVUV+Ey5AgslwfiEQCYRleGYMEgcYgVCiHgiEqRoQPlPcTinhZrwEE"
  "YoOEEz4OEWcMAQgENWBqbk6TlJV7lk4iYYScgwMvdkoSEQ0CE0ZqAS8TYwNJNRADAgwQEw"
  "N2akkFFXqYln+HExOzigHCE1OKyg1pxMpVGDlCIhU4OQgiCs8MQhaCamxUD99j5U2UUAnh"
  "PsAW2jkRWhQ1CdmJNYJhCp9CF1TfEtBIaDBhV6UDCMUUOLAAjoECCRY2pGBlwAIFCypYwF"
  "PAnZoKByTp0Ibg3QJDFBz/UVDQh8i3AQMCosnoqyYmYNty6tz5DOcALRYeTmtZw4CWCxUK"
  "yKmgBUOPfjoR8OJ14BNPYDsuWFVSQcTWM91eBLiV4CuRNGMK0MxDwYAhRThBTROx4IUBEf"
  "POjB1Q5sIYmVccAAB1gGqdAmwnvSkA2E+0MzEwfKKIwVoOCbjq9KUCgBxgg5MMlBtkB4Ha"
  "xHl2PGZQoKmFMhgUJPqGYEBHERdew75w4EVYHwLGJGpQm4GEtZYWGHgI0fQlOJGxKC1g+k"
  "CCPGp5GUA4RzmBHgwSSJhTNUEUGg5i5iBnp5fN95kw2Mm4IORKPAoMuKmKZ4IBBQGBdIAB"
  "LyzgyEVuPZJP/zKw3BNeHlDA90sLFFZo4YUm8KThhhzGxeGHICoRlwAUNIWBBeD5EIABFj"
  "QFVDVJHGBBXtsgUN8CRF21GgNl1FVDiY2pRkFjDDjAlCO/EeHAKz4QgAdbjO2ElRn/UPMM"
  "VDmwMoADV0zgnGIGbgNMPSe+5QMEQG3TjwBkIWCmkuSUM9ETFBTgjIg7PtDVCBZYdhcGFa"
  "gpQxgIMHlGBOYNWMc5ioHkCBEerlKiCL1FFugVEBDalytnTEAAAYlMEMccFRhA6EKWpONM"
  "pDmoZshRXCqB1hhleHHFN87swkudEXFSXaoHTDCmWTrIQIMERzG4yCblCJDkD54wwIYEyV"
  "GnkP2idqDaCzBaALhKraHOEtkF+nFpW4kXJIKlD6yI18ajhWHCXGkJGKBHfcz9mYMDNmpn"
  "iJe+mtbEVMox+B0Csb4QQSNsBDdABMi9h++TilFGBJsE0FsavZ+UklMgWznwzXfuSVjTHw"
  "cowNRDUCgAUQIYSQXgAhYIUFKBslTDAAULDCTtOmm8bEvEJt8kmY0YbXeBAp9aYKACB0i1"
  "QAMreapNAD3vrBKBEiTcxhh3rpJx0b5oMsjLmzwURgGOfOfKAFNAQACntCRhmzo2hEGAoQ"
  "4Msy8CokkQb9EiZLzx4QQg8QKbDtZwy6dzZ/xW33ATYQyXXh5eXHhzwLfADiEAADt7H9Hm";

